In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [9]:
import requests

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7",
    "Referer": "https://www.google.com/"
}

url = "https://www.lamudi.co.id/jual/"

response = requests.get(url, headers=headers)

print(response.status_code)

200

In [10]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "html.parser")

print(soup.title)

<title>Properti Dijual di Indonesia | Lamudi</title>

In [12]:
cards = soup.find_all("div", class_="snippet")

print("Jumlah Card:", len(cards))

Jumlah Card: 30

In [13]:
card = cards[0]

print(card.find("span", class_="snippet__content__title"))
print(card.find("div", class_="snippet__content__price"))
print(card.find("div", class_="snippet__content__location"))
print(card.find("a")["href"])

<span class="snippet__content__title" content="Rumah Dijual di Pesisir Selatan" itemprop="name">Rumah Dijual di Pesisir Selatan</span>
<div class="snippet__content__price">
                    Rp 2,10M
            </div>
<div class="snippet__content__location">
<span data-test="snippet-content-location">Kambang Barat, Pesisir Selatan, Sumatra Barat</span>
</div>
/properti/41032-73-2b88f097ff24-9218-197ee9b-9946-725c

In [14]:
data = []

for card in cards:

    # Judul
    judul = card.find("span", class_="snippet__content__title")
    judul = judul.get_text(strip=True) if judul else None

    # Harga
    harga = card.find("div", class_="snippet__content__price")
    harga = harga.get_text(strip=True) if harga else None

    # Lokasi
    lokasi = card.find("div", class_="snippet__content__location")
    lokasi = lokasi.get_text(" ", strip=True) if lokasi else None

    # Link
    link = card.find("a")["href"] if card.find("a") else None

    if link:
        link = "https://www.lamudi.co.id" + link

    data.append({
        "Judul": judul,
        "Harga": harga,
        "Lokasi": lokasi,
        "Link": link
    })

In [15]:
df = pd.DataFrame(data)

df.head()

,Judul,Harga,Lokasi,Link
0,Rumah Dijual di Pesisir Selatan,"Rp 2,10M","Kambang Barat, Pesisir Selatan, Sumatra Barat",https://www.lamudi.co.id/properti/41032-73-2b8...
1,Tanah Dijual di Pesisir Selatan,Rp 530Jt,"Kambang, Pesisir Selatan, Sumatra Barat",https://www.lamudi.co.id/properti/41032-73-38e...
2,Ruang Usaha Dijual di Depok,"Rp 5,50M","Manggung, Catur Tunggal, Depok, Sleman, Daerah...",https://www.lamudi.co.id/properti/41032-73-fab...
3,Ruang Usaha Dijual di Mlati,"Rp 5,70M","Sinduadi, Mlati, Sleman, Daerah Istimewa Yogya...",https://www.lamudi.co.id/properti/41032-73-dc6...
4,Rumah Dijual di Cikini,Rp 58M,"RW 02, Cikini, Menteng, Jakarta Pusat, Daerah ...",https://www.lamudi.co.id/properti/41032-73-ab3...

In [3]:
df.to_csv("lamudi_page1.csv", index=False, encoding="utf-8-sig")

print("Berhasil disimpan")

NameError: name 'df' is not defined

In [4]:
import pandas as pd

df = pd.read_csv("data/lamudi_page1.csv")

print(df.shape)
df.head()

(30, 4)

,Judul,Harga,Lokasi,Link
0,Rumah Dijual di Pesisir Selatan,"Rp 2,10M","Kambang Barat, Pesisir Selatan, Sumatra Barat",https://www.lamudi.co.id/properti/41032-73-2b8...
1,Tanah Dijual di Pesisir Selatan,Rp 530Jt,"Kambang, Pesisir Selatan, Sumatra Barat",https://www.lamudi.co.id/properti/41032-73-38e...
2,Ruang Usaha Dijual di Depok,"Rp 5,50M","Manggung, Catur Tunggal, Depok, Sleman, Daerah...",https://www.lamudi.co.id/properti/41032-73-fab...
3,Ruang Usaha Dijual di Mlati,"Rp 5,70M","Sinduadi, Mlati, Sleman, Daerah Istimewa Yogya...",https://www.lamudi.co.id/properti/41032-73-dc6...
4,Rumah Dijual di Cikini,Rp 58M,"RW 02, Cikini, Menteng, Jakarta Pusat, Daerah ...",https://www.lamudi.co.id/properti/41032-73-ab3...