In [35]:
import pandas as pd
import numpy as np
import re

In [36]:
df = pd.read_csv("data/lamudi_apartemen_detail_temp.csv")

print(df.shape)

df.head()

(2095, 15)

,Judul,Harga,Lokasi,Kota,Provinsi,Tipe Properti,Kamar Tidur,Kamar Mandi,Luas Total,Lantai,Tahun Dibangun,Sertifikat,Nama Agen,Tanggal Posting,Link
0,DIJUAL CEPAT UNIT STUDIO TOWER MATOA LT. 17 WO...,Rp 600Jt,"RW 07, Rawajati, Pancoran, Jakarta Selatan, Da...",Jakarta Selatan,Daerah Khusus Ibukota Jakarta,Apartemen,1 kamar tidur,1 kamar mandi,28 m²,17.0,2015.0,PPJB,MoFu,4 Jun 2026,https://www.lamudi.co.id/properti/41032-73-54c...
1,DI JUAL APARTEMEN 2 BEDROOM SKY HOUSE BSD – RE...,Rp 860Jt,"BSD City, Pagedangan, Pagedangan, Kabupaten Ta...",Kabupaten Tangerang,Banten,Apartemen,2 Kamar Tidur,1 kamar mandi,51 m²,19.0,2023.0,SHM,Frans Property,21 Mei 2026,https://www.lamudi.co.id/properti/41032-73-95c...
2,"Di jual 2BR Sky House BSD city, lokasi premium...",Rp 850Jt,"BSD City, Pagedangan, Pagedangan, Kabupaten Ta...",Kabupaten Tangerang,Banten,Apartemen,2 Kamar Tidur,1 kamar mandi,51 m²,20.0,2023.0,SHM,Frans Property,2 Jun 2026,https://www.lamudi.co.id/properti/41032-73-6b3...
3,INVESTASI TERBAIK 2026: 2BR SAMPING AEON BSD H...,Rp 840Jt,"BSD Grand CBD, BSD City, Pagedangan, Pagedanga...",Kabupaten Tangerang,Banten,Apartemen,2 Kamar Tidur,1 kamar mandi,48 m²,26.0,2027.0,SHM,Sky House BSD.,3 Jun 2026,https://www.lamudi.co.id/properti/41032-73-246...
4,Dijual Apartemen Sepinggan Terrace Balikpapan,Rp 600Jt,"Sepinggan Baru, Balikpapan Selatan, Balikpapan...",Balikpapan,Kalimantan Timur,Apartemen,NaN,1 kamar mandi,29 m²,NaN,NaN,NaN,Frans Property,10 Nov 2025,https://www.lamudi.co.id/properti/41032-73-f74...

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2095 entries, 0 to 2094
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Judul            2090 non-null   str
 1   Harga            2090 non-null   str
 2   Lokasi           2087 non-null   str
 3   Kota             2087 non-null   str
 4   Provinsi         2087 non-null   str
 5   Tipe Properti    2090 non-null   str
 6   Kamar Tidur      2033 non-null   str
 7   Kamar Mandi      2039 non-null   str
 8   Luas Total       2043 non-null   str
 9   Lantai           1576 non-null   float64
 10  Tahun Dibangun   426 non-null    float64
 11  Sertifikat       913 non-null    str
 12  Nama Agen        2090 non-null   str
 13  Tanggal Posting  2090 non-null   str
 14  Link             2095 non-null   str
dtypes: float64(2), str(13)
memory usage: 245.6 KB

In [38]:
df.isnull().sum()

Judul                 5
Harga                 5
Lokasi                8
Kota                  8
Provinsi              8
Tipe Properti         5
Kamar Tidur          62
Kamar Mandi          56
Luas Total           52
Lantai              519
Tahun Dibangun     1669
Sertifikat         1182
Nama Agen             5
Tanggal Posting       5
Link                  0
dtype: int64

In [39]:
missing = pd.DataFrame({
    "Missing": df.isnull().sum(),
    "Persentase (%)": round(df.isnull().mean()*100,2)
})

missing

                 Missing  Persentase (%)
Judul                  5            0.24
Harga                  5            0.24
Lokasi                 8            0.38
Kota                   8            0.38
Provinsi               8            0.38
Tipe Properti          5            0.24
Kamar Tidur           62            2.96
Kamar Mandi           56            2.67
Luas Total            52            2.48
Lantai               519           24.77
Tahun Dibangun      1669           79.67
Sertifikat          1182           56.42
Nama Agen              5            0.24
Tanggal Posting        5            0.24
Link                   0            0.00

In [40]:
df.duplicated().sum()

np.int64(0)

In [41]:
df = df.drop_duplicates(subset="Link")

In [42]:
def convert_price(x):

    if pd.isna(x):
        return np.nan

    x = x.replace("Rp","")
    x = x.replace(" ","")
    x = x.replace(",", ".")

    if "M" in x:
        return float(x.replace("M","")) * 1_000_000_000

    if "Jt" in x:
        return float(x.replace("Jt","")) * 1_000_000

    return np.nan

In [43]:
for harga in df["Harga"].unique():
    print(harga)

Rp 600Jt
Rp 860Jt
Rp 850Jt
Rp 840Jt
Rp 470Jt
Rp 500Jt
Mencari
Rp 1,40M
Rp 674,40Jt
Rp 3M
Rp 490Jt
Rp 600
Rp 450Jt
Rp 950Jt
Rp 2,40M
Rp 650Jt
Rp 1,03M
Rp 525Jt
Rp 195Jt
Rp 200Jt
Rp 644Jt
Rp 493,58Jt
Rp 328Jt
Rp 355Jt
Rp 898,58Jt
Rp 1,13M
Rp 1,86M
Rp 4,80M
Rp 6,50M
Rp 1,66M
Rp 2,20M
Rp 420Jt
Rp 935Jt
Rp 390Jt
Rp 1,30M
Rp 8,50M
Rp 20M
Rp 3,80M
Rp 870Jt
Rp 400Jt
Rp 930Jt
Rp 1,45M
Rp 1,65M
Rp 780Jt
Rp 300Jt
Rp 900Jt
Rp 1,20M
Rp 757Jt
Rp 2,30M
Rp 580Jt
Rp 275Jt
Rp 350Jt
Rp 942Jt
Rp 255Jt
Rp 75Jt/tahun
Rp 2,60M
Rp 3,30M
Rp 599Jt
Rp 6,90M
Rp 1,50M
Rp 3,50Jt/bulan
Rp 800Jt
Rp 1,90M
Rp 3,78M
Rp 3,24M
Rp 3,01M
Rp 2,93M
Rp 2,24M
Rp 980Jt
Rp 425Jt
Rp 23M
Rp 3,14M
Rp 1,25M
Rp 4,20M
Rp 435Jt
Rp 485Jt
Rp 2,35M
Rp 105Jt
Rp 165Jt
Rp 388Jt
Rp 125Jt
Rp 220Jt
Rp 430Jt
Rp 520Jt
Rp 30Jt/tahun
Rp 270Jt
Rp 16M
Rp 2,45M
Rp 115Jt
Rp 7M
Rp 3,70M
Rp 4,30M
Rp 345Jt
Rp 690Jt
Rp 790Jt
Rp 4,25M
Rp 1,58M
Rp 18,50M
Rp 975Jt
Rp 750Jt
Rp 550Jt
Rp 1,61M
Rp 875Jt
Rp 1,05M
Rp 660Jt
Rp 610Jt
Rp 1M
Rp 250Jt
Rp 399Jt
Rp 699Jt
Rp 3,69M
nan
Rp 12M
Rp 1,80M
Rp 625Jt
Rp 3,10M
Rp 3,49M
Rp 48M
Rp 13,50M
Rp 1,60M
Rp 12,70M
Rp 11,86M
Rp 1,10M
Rp 425M
Rp 180Jt
Rp 500,00Jt
Rp 850M
Rp 2M
Rp 25Jt/bulan
Rp 299Jt
Rp 15M
Rp 890Jt
Rp 3,50M
Rp 2,50M
Rp 3,20M
Rp 320Jt
Rp 2,10M
Rp 412Jt
Rp 939Jt
Rp 565Jt
Rp 13M
Rp 595Jt
Rp 1,35M
Rp 380Jt
Rp 5Jt/bulan
Rp 1,16M
Rp 399,99Jt
Rp 245Jt
Rp 1,18M
Rp 495Jt
Rp 1,19M
Rp 2,95M
Rp 2,18M
Rp 480Jt
Rp 260Jt
Rp 1,70M
Rp 155Jt
Rp 3,60M
Rp 315Jt
Rp 895Jt
Rp 190Jt
Rp 1,20Jt
Rp 4,50M
Rp 128,46Rb
Rp 225Jt
Rp 60Jt/tahun
Rp 2,50Jt/bulan
Rp 4M
Rp 12,48Rb/tahun
Rp 725Jt
Rp 18M
Rp 195Jt/tahun
Rp 375Jt
Rp 575Jt
Rp 1,39M
Rp 65Jt/tahun
Rp 396Jt
Rp 1,67M
Rp 700Jt
Rp 1,62M
Rp 180Jt/tahun
Rp 410Jt
Rp 285Jt
Rp 35M
Rp 280Jt
Rp 990Jt
Rp 1,78M
Rp 330Jt
Rp 50M
Rp 6Jt/bulan
Rp 69M
Rp 145Jt
Rp 120Jt/tahun
Rp 4,60M
Rp 17M
Rp 40Jt/tahun
Rp 27M
Rp 365Jt
Rp 925Jt
Rp 775Jt
Rp 865Jt
Rp 999Jt
Rp 310Jt
Rp 325Jt
Rp 150Jt
Rp 585Jt
Rp 73,50Jt/bulan
Rp 3,20Jt
Rp 570Jt
Rp 25Jt/tahun
Rp 2,65M
Rp 199Jt
Rp 715Jt
Rp 799Jt
Rp 100Jt/tahun
Rp 2,70M
Rp 7,50M
Rp 9,70M
Rp 5,50M
Rp 385Jt
Rp 400Rb/hari
Rp 13,50Jt/bulan
Rp 360Jt
Rp 33Jt/tahun
Rp 820Jt
Rp 9,90M
Rp 8,10M
Rp 445Jt
Rp 455Jt
Rp 43Jt/tahun
Rp 3,85M
Rp 670Jt
Rp 795Jt
Rp 699,99Jt
Rp 2,90M
Rp 5,70M
Rp 1,15M
Rp 2,85M
Rp 880Jt
Rp 459Jt
Rp 1,27M
Rp 2,80M
Rp 1,75M
Rp 665Jt
Rp 590Jt
Rp 510Jt
Rp 7Jt/bulan
Rp 470,00Jt
Rp 321,62Jt
Rp 499Jt
Rp 615Jt
Rp 340Jt
Rp 240Jt
Rp 640Jt
Rp 300Rb/hari
Rp 465Jt
Rp 313,51Jt
Rp 2,75M
Rp 295Jt
Rp 45Jt/tahun
Rp 1,55M
Rp 395Jt
Rp 28Jt/tahun
Rp 1,65Jt/bulan
Rp 1,95M
Rp 300Rb/bulan
Rp 210Jt
Rp 250Jt/tahun
Rp 4,15M
Rp 5,20M
Rp 189Jt
Rp 460Jt
Rp 405Jt
Rp 549Jt
Rp 139Jt
Rp 530Jt
Rp 3,35M
Rp 1,48M
Rp 1,22M
Rp 3,97M
Rp 17Jt/tahun
Rp 418Jt
Rp 760Jt
Rp 314,97Jt
Rp 630Jt
Rp 1,02M
Rp 19Jt/tahun
Rp 475Jt
Rp 680Jt
Rp 599,90Jt
Rp 582,49Jt
Rp 185Jt
Rp 175Jt
Rp 845Jt
Rp 899Jt
Rp 4,70M
Rp 230Jt
Rp 675Jt
Rp 18Jt/tahun
Rp 1,08M
Rp 1,59M
Rp 350,00Jt
Rp 540Jt
Rp 755Jt
Rp 5,30M
Rp 3,25M
Rp 900,00Jt
Rp 135Jt/tahun
Rp 158Jt
Rp 3,90M
Rp 13Jt/tahun
Rp 6,30Jt/bulan
Rp 940Jt
Rp 359,99Jt
Rp 160Jt
Rp 290Jt
Rp 730Jt
Rp 560Jt
Rp 499,99Jt
Rp 12,50Jt/bulan
Rp 1,49M
Rp 1,09M
Rp 998Jt
Rp 438Jt
Rp 678Jt
Rp 5M
Rp 22Jt/tahun
Rp 958Jt
Rp 995Jt
Rp 415Jt
Rp 130Jt/tahun
Rp 35Jt/tahun
Rp 80Jt/tahun
Rp 78Jt/tahun
Rp 535Jt
Rp 735Jt
Rp 47,50Jt/bulan
Rp 6,20M
Rp 65Jt/bulan
Rp 8,70M
Rp 50Jt/bulan
Rp 3,80Jt/bulan
Rp 249Jt
Rp 1,69M
Rp 33Jt/bulan
Rp 21M
Rp 44Jt/tahun
Rp 960Jt
Rp 21Jt/bulan
Rp 24Jt/bulan
Rp 3,30Jt/bulan
Rp 7,50Jt/bulan
Rp 265Jt
Rp 63Jt
Rp 5,45M
Rp 298Jt
Rp 8Jt/bulan
Rp 200Jt/bulan
Rp 6M
Rp 695Jt
Rp 1,38M
Rp 8M
Rp 8,80M
Rp 9,50M
Rp 8,90M
Rp 7,30M
Rp 10M
Rp 5,80M
Rp 7,10M
Rp 5,60M
Rp 21Jt/tahun
Rp 49Jt/tahun
Rp 835Jt
Rp 6,75M
Rp 130Jt
Rp 13Jt
Rp 45Jt/bulan
Rp 3,15M
Rp 970Jt
Rp 1,88M
Rp 3,26M
Rp 7,20M
Rp 14M
Rp 440Jt
Rp 11M
Rp 16,50M
Rp 16,58M
Rp 4,65M
Rp 29M
Rp 965Jt
Rp 594Jt
Rp 915Jt
Rp 2,48M
Rp 305Jt
Rp 2
Rp 3,75M
Rp 2,59M
Rp 2,15M
Rp 235Jt
Rp 700Rb
Rp 6,80M
Rp 4,75M
Rp 7,75M
Rp 140Jt/tahun
Rp 2,02M
Rp 785Jt
Rp 830Jt
Rp 3,81M
Rp 370Jt
Rp 2,34M
Rp 2,11M
Rp 5,33M
Rp 1,99M
Rp 2,49M
Rp 4,23M
Rp 1,85M
Rp 2,72M
Rp 2,96M
Rp 2,62M
Rp 3,08M
Rp 3,18M
Rp 2,69M
Rp 2,21M
Rp 3,53M
Rp 5,14M
Rp 6,62M
Rp 2,01M
Rp 2,52M
Rp 1,43M
Rp 1,77M
Rp 1,54M
Rp 2,14M
Rp 5,73M
Rp 3,37M
Rp 2,51M
Rp 9Jt
Rp 4,90M
Rp 11,50M
Rp 671,20Jt
Rp 2,00M
Rp 4,66M
Rp 558Jt
Rp 200Jt/tahun
Rp 279Jt
Rp 47,50Jt/tahun
Rp 545Jt
Rp 9M
Rp 28M
Rp 2,05M
Rp 5,90M
Rp 549,50Jt
Rp 34,70M
Rp 3,51M
Rp 765Jt
Rp 4,18M
Rp 4,19M
Rp 135Jt
Rp 629Jt
Rp 50Jt/tahun
Rp 629,44Jt
Rp 1,57M
Rp 1,26M
Rp 4,95M
Rp 8,75M
Rp 9,12M
Rp 770Jt
Rp 6,63M
Rp 727Jt
Rp 75M
Rp 650,00Jt
Rp 600,00Jt
Rp 17,80M
Rp 710Jt
Rp 740Jt
Rp 4Jt/bulan
Rp 215Jt
Rp 22Jt/bulan
Rp 1,29M
Rp 909Jt
Rp 953Jt
Rp 687Jt
Rp 668Jt
Rp 32M
Rp 2,97M
Rp 30,21M
Rp 602Jt
Rp 645Jt
Rp 1,68M
Rp 870,00Jt
Rp 780,00Jt
Rp 100Jt
Rp 1,98M
Rp 560
Rp 6,99M
Rp 1,07M
Rp 27Jt/tahun
Rp 3,29M
Rp 531Jt
Rp 5,75M
Rp 1,01M
Rp 528Jt
Rp 989Jt
Rp 188M
Rp 307Jt
Rp 150Jt/tahun
Rp 220Jt/tahun
Rp 250M
Rp 39M
Rp 6,60M
Rp 14,50M
Rp 7,90M
Rp 6,25M
Rp 12,50M
Rp 720Jt
Rp 605Jt
Rp 635Jt
Rp 3,64M
Rp 515Jt
Rp 1,92M
Rp 9,80M
Rp 1,53M
Rp 3,40M
Rp 4,50Jt/bulan
Rp 100M
Rp 999,00Jt
Rp 2,29M

In [44]:
df = df.dropna(subset=["Harga"])

df = df[df["Harga"] != "Mencari"]

# Hapus harga sewa
df = df[
    ~df["Harga"].str.contains(
        "bulan|tahun|hari",
        case=False,
        na=False
    )
]

In [45]:
print(df.shape)

(1996, 15)

In [46]:
def convert_price(x):

    if pd.isna(x):
        return np.nan

    x = str(x).strip()

    # Harus diawali Rp
    if not x.startswith("Rp"):
        return np.nan

    # Hilangkan Rp
    x = x.replace("Rp", "").strip()

    # Ambil angka + satuan
    match = re.match(r"([\d.,]+)\s*(Rb|Jt|M)?", x)

    if not match:
        return np.nan

    angka = match.group(1).replace(",", ".")
    satuan = match.group(2)

    try:
        angka = float(angka)
    except ValueError:
        return np.nan

    if satuan == "Rb":
        return angka * 1_000

    elif satuan == "Jt":
        return angka * 1_000_000

    elif satuan == "M":
        return angka * 1_000_000_000

    else:
        return angka

In [47]:
df["Harga"] = df["Harga"].apply(convert_price)

In [48]:
df["Harga"].head()

0    600000000.0
1    860000000.0
2    850000000.0
3    840000000.0
4    600000000.0
Name: Harga, dtype: float64

In [49]:
def convert_area(x):

    if pd.isna(x):
        return np.nan

    angka = re.findall(r"\d+", x)

    if angka:
        return int(angka[0])

    return np.nan

In [50]:
df["Luas Total"] = df["Luas Total"].apply(convert_area)

In [51]:
def convert_number(x):

    if pd.isna(x):
        return np.nan

    # Jika sudah angka, langsung kembalikan
    if isinstance(x, (int, float)):
        return x

    x = str(x)

    angka = re.findall(r"\d+", x)

    if angka:
        return int(angka[0])

    return np.nan

In [52]:
df["Kamar Tidur"] = df["Kamar Tidur"].apply(convert_number)
df["Kamar Mandi"] = df["Kamar Mandi"].apply(convert_number)

In [53]:
df.info()

<class 'pandas.DataFrame'>
Index: 1996 entries, 0 to 2094
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Judul            1996 non-null   str
 1   Harga            1996 non-null   float64
 2   Lokasi           1993 non-null   str
 3   Kota             1993 non-null   str
 4   Provinsi         1993 non-null   str
 5   Tipe Properti    1996 non-null   str
 6   Kamar Tidur      1943 non-null   float64
 7   Kamar Mandi      1948 non-null   float64
 8   Luas Total       1952 non-null   float64
 9   Lantai           1512 non-null   float64
 10  Tahun Dibangun   408 non-null    float64
 11  Sertifikat       868 non-null    str
 12  Nama Agen        1996 non-null   str
 13  Tanggal Posting  1996 non-null   str
 14  Link             1996 non-null   str
dtypes: float64(6), str(9)
memory usage: 249.5 KB

In [54]:
df.drop(columns=["Tahun Dibangun", "Sertifikat"], inplace=True)

In [55]:
df.info()

<class 'pandas.DataFrame'>
Index: 1996 entries, 0 to 2094
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Judul            1996 non-null   str
 1   Harga            1996 non-null   float64
 2   Lokasi           1993 non-null   str
 3   Kota             1993 non-null   str
 4   Provinsi         1993 non-null   str
 5   Tipe Properti    1996 non-null   str
 6   Kamar Tidur      1943 non-null   float64
 7   Kamar Mandi      1948 non-null   float64
 8   Luas Total       1952 non-null   float64
 9   Lantai           1512 non-null   float64
 10  Nama Agen        1996 non-null   str
 11  Tanggal Posting  1996 non-null   str
 12  Link             1996 non-null   str
dtypes: float64(5), str(8)
memory usage: 218.3 KB

In [56]:
print(df.shape)

df.head()

(1996, 13)

,Judul,Harga,Lokasi,Kota,Provinsi,Tipe Properti,Kamar Tidur,Kamar Mandi,Luas Total,Lantai,Nama Agen,Tanggal Posting,Link
0,DIJUAL CEPAT UNIT STUDIO TOWER MATOA LT. 17 WO...,600000000.0,"RW 07, Rawajati, Pancoran, Jakarta Selatan, Da...",Jakarta Selatan,Daerah Khusus Ibukota Jakarta,Apartemen,1.0,1.0,28.0,17.0,MoFu,4 Jun 2026,https://www.lamudi.co.id/properti/41032-73-54c...
1,DI JUAL APARTEMEN 2 BEDROOM SKY HOUSE BSD – RE...,860000000.0,"BSD City, Pagedangan, Pagedangan, Kabupaten Ta...",Kabupaten Tangerang,Banten,Apartemen,2.0,1.0,51.0,19.0,Frans Property,21 Mei 2026,https://www.lamudi.co.id/properti/41032-73-95c...
2,"Di jual 2BR Sky House BSD city, lokasi premium...",850000000.0,"BSD City, Pagedangan, Pagedangan, Kabupaten Ta...",Kabupaten Tangerang,Banten,Apartemen,2.0,1.0,51.0,20.0,Frans Property,2 Jun 2026,https://www.lamudi.co.id/properti/41032-73-6b3...
3,INVESTASI TERBAIK 2026: 2BR SAMPING AEON BSD H...,840000000.0,"BSD Grand CBD, BSD City, Pagedangan, Pagedanga...",Kabupaten Tangerang,Banten,Apartemen,2.0,1.0,48.0,26.0,Sky House BSD.,3 Jun 2026,https://www.lamudi.co.id/properti/41032-73-246...
4,Dijual Apartemen Sepinggan Terrace Balikpapan,600000000.0,"Sepinggan Baru, Balikpapan Selatan, Balikpapan...",Balikpapan,Kalimantan Timur,Apartemen,NaN,1.0,29.0,NaN,Frans Property,10 Nov 2025,https://www.lamudi.co.id/properti/41032-73-f74...

In [57]:
df["Tanggal Posting"].unique()

<StringArray>
[                '4 Jun 2026',                '21 Mei 2026',
                 '2 Jun 2026',                 '3 Jun 2026',
                '10 Nov 2025',                 '2 Jan 2026',
                 '6 Jun 2026',                 '9 Mar 2026',
                '30 Apr 2026',                 '9 Mei 2026',
 ...
                '28 Sep 2024',                '17 Mar 2024',
                '15 Mar 2024',                '14 Mar 2024',
    '1 hari, 4 jam yang lalu',  '2 minggu, 9 jam yang lalu',
                '26 Okt 2025', '1 minggu, 12 jam yang lalu',
                '24 Agu 2024',                '14 Agu 2024']
Length: 566, dtype: str

In [58]:
df["Tanggal Posting"].value_counts(dropna=False)

Tanggal Posting
28 Mei 2026                  28
8 Jun 2026                   26
1 Jun 2026                   25
5 Jun 2026                   25
2 Jun 2026                   24
                             ..
14 Mar 2024                   1
2 minggu, 9 jam yang lalu     1
26 Okt 2025                   1
24 Agu 2024                   1
14 Agu 2024                   1
Name: count, Length: 566, dtype: int64

In [59]:
df.drop(columns=["Tanggal Posting"], inplace=True)

In [60]:
df.info()

<class 'pandas.DataFrame'>
Index: 1996 entries, 0 to 2094
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Judul          1996 non-null   str
 1   Harga          1996 non-null   float64
 2   Lokasi         1993 non-null   str
 3   Kota           1993 non-null   str
 4   Provinsi       1993 non-null   str
 5   Tipe Properti  1996 non-null   str
 6   Kamar Tidur    1943 non-null   float64
 7   Kamar Mandi    1948 non-null   float64
 8   Luas Total     1952 non-null   float64
 9   Lantai         1512 non-null   float64
 10  Nama Agen      1996 non-null   str
 11  Link           1996 non-null   str
dtypes: float64(5), str(7)
memory usage: 202.7 KB

In [68]:
df["Kota"].unique()

<StringArray>
[              'Jakarta Selatan',           'Kabupaten Tangerang',
                    'Balikpapan',                  'Kota Bandung',
                      'Makassar',                 'Jakarta Utara',
                    'Kab Bekasi',             'Tangerang Selatan',
                        'Badung',                 'Jakarta Timur',
                     'Tangerang',                       'Gianyar',
                       'Tabanan',                 'Jakarta Pusat',
                     'Kab Bogor',                      'Surabaya',
                         'Depok',                 'Jakarta Barat',
                     'Surakarta',                    'Batam Kota',
                        'Bekasi',                         'Bogor',
                    'Kota Medan', 'Daerah Khusus Ibukota Jakarta',
                      'Denpasar',                 'Kota Semarang',
                   'Karanganyar',                      'Sumedang',
                        'Sleman',                      'Karawang',
                      'Sidoarjo',                    'Lubuk Baja',
                     'Sukoharjo',                          'Palu',
                'Bandar Lampung',             'Kabupaten Cirebon',
                  'Barito Kuala',                     'Lowokwaru',
                   'Kota Malang',                     'Jeneponto',
                     'Palembang',                        'Nongsa',
                        'Jember',                    'Bojonegoro',
                    'Kab Serang',             'Kabupaten Bandung',
                      'Kuningan']
Length: 47, dtype: str

In [62]:
missing = pd.DataFrame({
    "Missing": df.isnull().sum(),
    "Persentase (%)": round(df.isnull().mean()*100,2)
})

missing

               Missing  Persentase (%)
Judul                0            0.00
Harga                0            0.00
Lokasi               3            0.15
Kota                 3            0.15
Provinsi             3            0.15
Tipe Properti        0            0.00
Kamar Tidur         53            2.66
Kamar Mandi         48            2.40
Luas Total          44            2.20
Lantai             484           24.25
Nama Agen            0            0.00
Link                 0            0.00

In [63]:
df.drop(columns=["Lantai"], inplace=True)

In [64]:
df["Kamar Tidur"] = df["Kamar Tidur"].fillna(df["Kamar Tidur"].median())

df["Kamar Mandi"] = df["Kamar Mandi"].fillna(df["Kamar Mandi"].median())

df["Luas Total"] = df["Luas Total"].fillna(df["Luas Total"].median())

In [65]:
df = df.dropna(subset=["Lokasi", "Kota", "Provinsi"])

In [66]:
df.isnull().sum()

Judul            0
Harga            0
Lokasi           0
Kota             0
Provinsi         0
Tipe Properti    0
Kamar Tidur      0
Kamar Mandi      0
Luas Total       0
Nama Agen        0
Link             0
dtype: int64

In [69]:
print(df.shape)

df.head()

(1993, 11)

,Judul,Harga,Lokasi,Kota,Provinsi,Tipe Properti,Kamar Tidur,Kamar Mandi,Luas Total,Nama Agen,Link
0,DIJUAL CEPAT UNIT STUDIO TOWER MATOA LT. 17 WO...,600000000.0,"RW 07, Rawajati, Pancoran, Jakarta Selatan, Da...",Jakarta Selatan,Daerah Khusus Ibukota Jakarta,Apartemen,1.0,1.0,28.0,MoFu,https://www.lamudi.co.id/properti/41032-73-54c...
1,DI JUAL APARTEMEN 2 BEDROOM SKY HOUSE BSD – RE...,860000000.0,"BSD City, Pagedangan, Pagedangan, Kabupaten Ta...",Kabupaten Tangerang,Banten,Apartemen,2.0,1.0,51.0,Frans Property,https://www.lamudi.co.id/properti/41032-73-95c...
2,"Di jual 2BR Sky House BSD city, lokasi premium...",850000000.0,"BSD City, Pagedangan, Pagedangan, Kabupaten Ta...",Kabupaten Tangerang,Banten,Apartemen,2.0,1.0,51.0,Frans Property,https://www.lamudi.co.id/properti/41032-73-6b3...
3,INVESTASI TERBAIK 2026: 2BR SAMPING AEON BSD H...,840000000.0,"BSD Grand CBD, BSD City, Pagedangan, Pagedanga...",Kabupaten Tangerang,Banten,Apartemen,2.0,1.0,48.0,Sky House BSD.,https://www.lamudi.co.id/properti/41032-73-246...
4,Dijual Apartemen Sepinggan Terrace Balikpapan,600000000.0,"Sepinggan Baru, Balikpapan Selatan, Balikpapan...",Balikpapan,Kalimantan Timur,Apartemen,2.0,1.0,29.0,Frans Property,https://www.lamudi.co.id/properti/41032-73-f74...

In [70]:
df.to_csv(
    "data/lamudi_apartemen_clean.csv",
    index=False,
    encoding="utf-8-sig"
)